name: Continuous Integration
on:
    # Every push
    push:
    schedule:
        # Every Monday and Thursday at 12PM UTC
        - cron: '0 12 * * 1,4'

jobs:
    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                node-version: [ 10.x, 12.x, 13.x ]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: ./node_modules/.bin/nyc --reporter=lcovonly npm test
        - uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
