{
    "name": "Continuous Integration",
    "on": {
        # Every push
        "push": {},
        "schedule": [
            {
                # Every Monday and Thursday at 12PM UTC
                "cron": "0 12 * * 1,4"
            }
        ]
    },
    "jobs": {
        "test": {
            "strategy": {
                "matrix": {
                    "os": [
                        "ubuntu-latest",
                        "macos-latest",
                        "windows-latest"
                    ],
                    "node-version": [
                        "10.x",
                        "12.x",
                        "13.x"
                    ]
                }
            },
            "runs-on": "${{ matrix.os }}",
            "steps": [
                {
                    "name": "Checkout",
                    "uses": "actions/checkout@v1"
                },
                {
                    "name": "Setup node",
                    "uses": "actions/setup-node@v1",
                    "with": {
                        "node-version": "${{ matrix.node-version }}"
                    }
                },
                {
                    "name": "Install dependencies",
                    "run": "npm ci"
                },
                {
                    "name": "Run tests",
                    "run": "./node_modules/.bin/nyc --reporter=lcovonly npm test"
                },
                {
                    "name": "Push coverage to Codecov",
                    "uses": "codecov/codecov-action@v1",
                    "with": {
                        "token": "${{ secrets.CODECOV_UPLOAD_TOKEN }}"
                    }
                }
            ]
        },
        "release-readiness": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "Checkout",
                    "uses": "actions/checkout@v1"
                },
                {
                    "name": "Setup node",
                    "uses": "actions/setup-node@v1",
                    "with": {
                        "node-version": "13.x"
                    }
                },
                {
                    "name": "Install cspell",
                    "run": "npm i -g cspell"
                },
                {
                    "name": "Check spelling",
                    "run": "cspell 'src/**/*.ts'"
                }
            ]
        }
    }
}
